"""Update characters table

Revision ID: db2911d50803
Revises: 488837999222
Create Date: 2025-02-05 20:09:11.434283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2911d50803'
down_revision = '488837999222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('strength',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('strength',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
